### PR TITLE
MM-820: Update to Gytheio 0.10.x (=> 0.10.1)

### PR DESCRIPTION
**Pull request by montgolfiere**
- TODO: ACS Packaging once we have next corresponding release of alfresco-repository.jar
- https://github.com/Alfresco/acs-packaging/pull/418

### CODE REVIEW

**Comment by montgolfiere** [comment]
Note: I'd like to see if we can get this in for next ACS Repo 6.2.0 release candidate (ie. A7 or RC1). We can then create MM 1.4.0-RC1 ?

**Comment by montgolfiere** [comment]
Yes, thanks. I will also open PR for ACS Packaging imminently (pending Repo 7.xx version).

**Comment by ancutam** [comment]
Is PR #569 (MM-811: Update Gytheio (Messaging Camel) from 0.9.1 to 0.1)  still valid?

**Comment by montgolfiere** [comment]
@ancutam No, good catch - I will close it without merge.

**Comment by montgolfiere** [comment]
Comment bump (for JIRA).

**Pull request merged**
